---
title: "Food Availability Model"
author: "Nick Strayer"
date: "March 12, 2015"
output: html_document
---

```{r}
library(ggplot2)
# Code for a simple food availability model based upon the assumptions of higher pelagic food quality
# in the summer. 
```

## Parameters We Set: 

```{r}
#First we set up some user defined variables. 
min     = 0.15 #minimum food availability value
max     = 0.97 #max 
highDay = 210*24 #Number of days into the year that the max food availability is (226 is aug 15)
august  = 5856 #hours into the year
```

## The actual model

```{r}
#Now we generate the others
scaler    = (max - min)/2 #range divided by two
heightAdj = (max + min)/2 #average value
hours      = 1:(365*24) #Set up a hour vector to loop over
foodAvail = NULL  

#Quick loop to generate the data. 
for (hour in hours){
  foodAvail = c(foodAvail, scaler * cos( (1/(365*24))*2*pi * (hour - highDay)) + heightAdj)
}

qplot(hours,foodAvail, geom = "line", main = "Food Availability Over Year")
setwd("/Users/Nick/mysisModeling/paperMaterials/figures")
ggsave(filename = "foodAvailability.pdf", width = 6, height = 4.5)
```

## The variability curve

Here we set up another curve which represents the variablity of the food distribution at any time. 

The value of the curve $f(hour) =$ variability of distribution. 


```{r}
min     = 0.1 #minimum food availability value
max     = 0.9 #max 
highDay = 100*24
scaler    = (max - min)/2 #range divided by two
heightAdj = (max + min)/2 #average value
variability = NULL

#Quick loop to generate the data. 
for (hour in hours){
  variability = c(variability, scaler * cos( (1/(365*24))*4*pi * (hour - highDay)) + heightAdj)
}

qplot(hours,variability, geom = "line", main = "Food Variability")
setwd("/Users/Nick/mysisModeling/paperMaterials/figures")
ggsave(filename = "foodVariability.pdf", width = 6, height = 4.5)

avail_var_df = as.data.frame(cbind(foodAvail, variability))
```

## Combined curves:

We will now generate the bounding curves by adding and subtracting the variablity from the main curve. 

```{r}
highBound = NULL
lowBound  = NULL

for (hour in hours){
  highBound = c(highBound, (foodAvail[hour] + variability[hour]))  
  lowBound = c(lowBound, (foodAvail[hour] - variability[hour]))
}

distributionDf = as.data.frame(cbind(hours, highBound, lowBound))

library(ggplot2)

ggplot(distributionDf, aes(hours)) + 
  geom_line(aes(y = highBound, colour = "#beaed4")) + 
  geom_line(aes(y = lowBound, colour = "#7fc97f")) 

```

## Save to file 
```{r}
setwd("/Users/Nick/mysisModeling")
#write.csv(distributionDf, "data/FoodAvail_Hour.csv", row.names=FALSE) #The bounded model  #
#write.csv(avail_var_df, "data/FoodAvail_Hour.csv", row.names=FALSE) #The plain side curve. 

```

```{r echo=FALSE}
library(ggplot2)
migrationProb = function(condition){ #I am choosing to leave the random roll outside of script for continuity, could be changed
  m = 120 #value of curve midpoint
  k = 0.03 #steepness of curve
  x = condition 
  
  dist = 1/(1 + exp(-k* (x - m)))   
  return(1 - dist)
}


condition = seq(1,240, 0.1)
results = sapply(condition, migrationProb)
qplot(condition, results, geom = "line", main = "Migration Probability By Condition", ylab = "Prob. of Migration")
setwd("/Users/Nick/mysisModeling/paperMaterials/figures")
ggsave(filename = "migrationProb.pdf", width = 6, height = 4.5)

```